import xml.etree.ElementTree as ET
import urllib


xml = '''
<commentinfo>
<note>
This file contains the actual data for your assignment - good luck!
</note>
<comments>
<comment>
<name>Tamiem</name>
<count>97</count>
</comment>
<comment>
<name>Madison</name>
<count>94</count>
</comment>
<comment>
<name>Manolo</name>
<count>90</count>
</comment>
<comment>
<name>Ubayd</name>
<count>88</count>
</comment>
<comment>
<name>Divya</name>
<count>88</count>
</comment>
<comment>
<name>Mandy</name>
<count>87</count>
</comment>
<comment>
<name>Domenico</name>
<count>76</count>
</comment>
<comment>
<name>Cari</name>
<count>76</count>
</comment>
<comment>
<name>Jorgie</name>
<count>74</count>
</comment>
<comment>
<name>Avesta</name>
<count>73</count>
</comment>
<comment>
<name>Rehan</name>
<count>72</count>
</comment>
<comment>
<name>Neelam</name>
<count>72</count>
</comment>
<comment>
<name>Sanjay</name>
<count>68</count>
</comment>
<comment>
<name>Eryk</name>
<count>64</count>
</comment>
<comment>
<name>Marla</name>
<count>62</count>
</comment>
<comment>
<name>Alanah</name>
<count>54</count>
</comment>
<comment>
<name>Poppie</name>
<count>54</count>
</comment>
<comment>
<name>Deimante</name>
<count>53</count>
</comment>
<comment>
<name>Elijah</name>
<count>50</count>
</comment>
<comment>
<name>Digby</name>
<count>50</count>
</comment>
<comment>
<name>Dexter</name>
<count>49</count>
</comment>
<comment>
<name>Graidi</name>
<count>49</count>
</comment>
<comment>
<name>Sharlyn</name>
<count>49</count>
</comment>
<comment>
<name>Darryn</name>
<count>46</count>
</comment>
<comment>
<name>Alannah</name>
<count>45</count>
</comment>
<comment>
<name>Nialla</name>
<count>45</count>
</comment>
<comment>
<name>Dean</name>
<count>41</count>
</comment>
<comment>
<name>Zalfa</name>
<count>38</count>
</comment>
<comment>
<name>Ivan</name>
<count>34</count>
</comment>
<comment>
<name>Lorna</name>
<count>34</count>
</comment>
<comment>
<name>Deon</name>
<count>32</count>
</comment>
<comment>
<name>Phoebe</name>
<count>30</count>
</comment>
<comment>
<name>Krzysiek</name>
<count>27</count>
</comment>
<comment>
<name>Lexie</name>
<count>27</count>
</comment>
<comment>
<name>Boab</name>
<count>24</count>
</comment>
<comment>
<name>Xavier</name>
<count>24</count>
</comment>
<comment>
<name>Frank</name>
<count>22</count>
</comment>
<comment>
<name>Rylie</name>
<count>22</count>
</comment>
<comment>
<name>Eubh</name>
<count>18</count>
</comment>
<comment>
<name>Maxx</name>
<count>17</count>
</comment>
<comment>
<name>Rahma</name>
<count>16</count>
</comment>
<comment>
<name>Kelsey</name>
<count>15</count>
</comment>
<comment>
<name>Kaisha</name>
<count>10</count>
</comment>
<comment>
<name>Vincent</name>
<count>9</count>
</comment>
<comment>
<name>Toluwani</name>
<count>8</count>
</comment>
<comment>
<name>Yasmeen</name>
<count>6</count>
</comment>
<comment>
<name>Darcie</name>
<count>6</count>
</comment>
<comment>
<name>Davy</name>
<count>3</count>
</comment>
<comment>
<name>Kristopher</name>
<count>1</count>
</comment>
<comment>
<name>Sultan</name>
<count>1</count>
</comment>
</comments>
</commentinfo>'''

root = ET.fromstring(xml)

list = root.findall('.//count')
sum = 0
for item in list:
    sum += int(item.text)

print sum
